name: hdos
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.migra
    container_name: hdos-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://hodom:hodom@hodom-pg:5432/hodom
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hdos.rule=Host(`hdos.sanixai.com`)"
      - "traefik.http.routers.hdos.entrypoints=websecure"
      - "traefik.http.routers.hdos.tls.certresolver=myresolver"
      - "traefik.http.services.hdos.loadbalancer.server.port=8501"

networks:
  web:
    external: true
