-- CORR-07: Completitud y normalización final
-- Fecha: 2026-04-07
--
-- 1. condicion.descripcion:
--    - Prefijos numéricos residuales eliminados ('0 INFECCION...' → 'INFECCION...')
--    - Typos: PETROCANTERIANA, SREPTOCOCCUS, EMOLIA, INSUFIENCIA, PIEOLONEFRITIS, OSTEOMELITIS
--    - Consolidación semántica: FX→FRACTURA, variantes de neumonía/ITU/ACV unificadas
--    - 415 → 383 descripciones únicas
--
-- 2. diagnostico_principal en estadías:
--    - 30 diagnósticos texto mapeados a formato CIE10-DESC
--    - 297 → 246 valores únicos, 95 restantes sin CIE-10 (diagnósticos raros/compuestos)
--
-- 3. estado_actual paciente:
--    - 19 pacientes con NULL → derivado de fecha_egreso en estadías
--    - 673/673 con estado (26 activo, 647 egresado)
--
-- 4. contacto_telefono:
--    - 471/673 pacientes con teléfono (desde raw CSVs + formularios HODOM)
--
-- 5. direccion:
--    - 480/673 pacientes con dirección (desde raw CSVs + formularios)
--
-- Completitud final clinical.paciente:
--   nombre 673, rut 673, sexo 673, fdn 672, dirección 480,
--   comuna_real 564, cesfam_real 559, previsión 642, teléfono 471, estado 673
