-- CORR-04: Poblar previsión en clinical.paciente
-- Fecha: 2026-04-07
-- Contexto: 673 pacientes con prevision NULL.
-- Fuentes: raw CSV exports (PREVISIÓN), formularios HODOM (PREVISIÓN),
--          canonical hospitalization_stay.csv (prevision).
-- Resultado: 642 actualizados, 31 sin dato en ninguna fuente.
--
-- Normalización aplicada:
--   FONASA A → fonasa-a, FONASA B → fonasa-b, FONASA C → fonasa-c,
--   FONASA D → fonasa-d, FONASA (sin tramo) → fonasa-b, PRAIS → prais
--   Typos: FONADA D → fonasa-d, FOBASA B → fonasa-b, FONSA A → fonasa-a
--
-- Distribución final:
--   fonasa-b: 532, fonasa-a: 43, fonasa-d: 31, fonasa-c: 27, prais: 9, NULL: 31
--
-- Ejecutado via Python (multi-source collection + normalization + UPDATE).
-- Proveniencia registrada en migration.provenance fase CORR-04.
