-- CORR-06: Normalización global de datos tipográficos y semánticos
-- Fecha: 2026-04-07
-- Contexto: revisión de todas las tablas para inconsistencias de tipeo y presentación.
--
-- 1. necesidad_profesional:
--    - KNT → KINESIOLOGIA (2 registros)
--    - FONO → FONOAUDIOLOGIA (1)
--    - nivel_necesidad 'si' → 'SI' (2)
--    Resultado: 4 profesiones limpias (ENFERMERIA 504, KINESIOLOGIA 390, FONOAUDIOLOGIA 123, MEDICO 1)
--
-- 2. rem_prestacion en visitas:
--    - 1065 variantes → 120 tipos normalizados
--    - Formato: componentes atómicos separados por + (KTM, KTR, FONO, CA, CS, TTO_EV, etc.)
--    - Compuestos: ING_ENF+TTO_EV+VM_ING (visita de ingreso con tratamiento y VM)
--    - Basura ($, ?, .) → NULL
--
-- 3. condicion (diagnósticos):
--    - 958 condiciones actualizadas con código CIE-10 extraído/asignado
--    - Descripciones normalizadas (ITU → INFECCION DE VIAS URINARIAS, ACV → ACCIDENTE VASCULAR, etc.)
--    - 958/1246 ahora con codigo_cie10 (antes: 0)
--    - 446 → 415 descripciones únicas
--
-- 4. diagnostico_principal en estadías:
--    - Formato 'texto | CIE10' descompuesto → solo CIE10-DESCRIPCION
--    - Abreviados mapeados (ITU, NEUMONIA, ACV, etc.) a código CIE-10 canónico
--    - Variantes del mismo código consolidadas (N39.0-... todas → N39.0-INFECCION DE VIAS URINARIAS)
--    - 297 → 259 valores únicos
--    - Top: N39.0 (143), J18.9 (71), I64 (54), J96.0 (23)
--
-- Ejecutado via Python + SQL directo. Proveniencia implícita.
